# Generated by Django 5.0.2 on 2024-02-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0002_publication_researchproject_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
    ]
