# Generated by Django 5.0.2 on 2024-02-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0006_userprofile_github_userprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
