# Generated by Django 5.0.2 on 2024-02-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0008_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='Default Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='Default education', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(default='Default position', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='research_interests',
            field=models.TextField(default='Default research interest'),
        ),
    ]
