# Generated by Django 5.0.2 on 2024-02-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0011_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_info',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
