# Generated by Django 5.0.2 on 2024-02-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
