# Generated by Django 5.0.2 on 2024-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0020_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
