# Generated by Django 5.0.2 on 2024-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0021_userprofile_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
