# Generated by Django 5.0.2 on 2024-02-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0022_remove_userprofile_file_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
