# Generated by Django 5.0.2 on 2024-02-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0024_userprofile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_photo',
            new_name='profile_photos',
        ),
    ]
