# Generated by Django 5.0.2 on 2024-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0025_rename_profile_photo_userprofile_profile_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photos',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
