# Generated by Django 5.0.2 on 2024-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0026_remove_userprofile_profile_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
