# Generated by Django 5.0.2 on 2024-02-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0027_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
    ]
