# Generated by Django 5.0.2 on 2024-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0028_userprofile_email_userprofile_otp_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
