# Generated by Django 5.0.2 on 2024-02-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0029_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
    ]
