# Generated by Django 5.0.2 on 2024-02-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0030_remove_userprofile_otp_sent_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
